### PR TITLE
Noarch Python

### PR DESCRIPTION
**Pull request by xmnlab**

### CODE REVIEW

**Comment by jakirkham** [comment]
So this is just to add Python 3.6, correct? Wondering if makes sense to take this package down the [`noarch: python`]( http://conda-forge.readthedocs.io/en/latest/meta.html#building-noarch-packages ) path. Seems like a good candidate from a cursory glance.

**Comment by xmnlab** [comment]
@jakirkham done! thanks!

**Comment by xmnlab** [comment]
@jakirkham yes .. this rerender was just to add the python3.6 ... I don't know why the last rerender didn't work ...

**Comment by jakirkham** [comment]
@conda-forge-admin, please rerender. :)

**Comment by jakirkham** [comment]
Cool. So we need to re-render after adding `noarch: python` as this changes how (and which CIs) we use. Asked the bot to do that for us to keep life simple. :)

**Comment by xmnlab** [comment]
@jakirkham thanks!

**Comment by xmnlab** [comment]
@conda-forge-admin, please rerender

**Comment by xmnlab** [comment]
@jakirkham 

has the rerender command (conda-forge-admin) worked?

**Comment by jakirkham** [comment]
Yes, I had asked it to re-render previously to save you the trouble. :) Think that got lost in our communication though. Sorry about that. :(

**Comment by xmnlab** [comment]
ohh sorry ... and thank you a lot!
can this already be merged? or is missing something else?

**Comment by jakirkham** [comment]
One more thing that I just noticed. This seems to have a `bld.bat` floating around in the `recipe`. That is a very old `conda-build` workaround for the `meta.yaml` `script` section not working on Windows that has long since been fixed. Could you please remove the `bld.bat`? This goes well with the `noarch` change.

**Comment by xmnlab** [comment]
@jakirkham done! Thank you a lot!

**Comment by xmnlab** [comment]
@jakirkham is it ok to be merged?

**Comment by jakirkham** [comment]
Seems fine to me, but I'd rather defer to the feedstock maintainer. @kwilcox, could you please take a look when you have a chance?

**Comment by kwilcox** [comment]
@xmnlab Please consider adding yourself as a maintainer of this feedstock! I have switched to http://whitenoise.evans.io/en/stable/ for most everything and haven't followed dj-static releases in awhile.

**Comment by xmnlab** [comment]
@kwilcox OK! thank you!

**Pull request merged**
